package com.example.poolcalculator

import android.content.Context
import android.content.Intent
import android.graphics.Color
import android.graphics.Paint
import android.graphics.Typeface
import android.graphics.pdf.PdfDocument
import android.net.Uri
import android.widget.Toast
import androidx.core.content.FileProvider
import java.io.File
import java.io.FileOutputStream
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

object Exporter {

    fun makePdf(ctx: Context, title: String, rows: List<Pair<String, String>>): Uri? = try {
        val doc = PdfDocument()
        val page = doc.startPage(PdfDocument.PageInfo.Builder(595, 842, 1).create())
        val c = page.canvas

        val head = Paint().apply {
            color = Color.parseColor("#00696E"); textSize = 22f; isAntiAlias = true
            typeface = Typeface.create("sans-serif", Typeface.BOLD)
        }
        val sub = Paint().apply { color = Color.GRAY; textSize = 11f; isAntiAlias = true }
        val key = Paint().apply { color = Color.DKGRAY; textSize = 12f; isAntiAlias = true }
        val valP = Paint().apply {
            color = Color.BLACK; textSize = 12f; isAntiAlias = true
            typeface = Typeface.create("sans-serif", Typeface.BOLD)
            textAlign = Paint.Align.RIGHT
        }
        val line = Paint().apply { color = Color.LTGRAY; strokeWidth = 1f }

        var y = 60f
        c.drawText("Swimming Pool Estimate", 40f, y, head); y += 18f
        c.drawText(title, 40f, y, sub); y += 14f
        c.drawText(SimpleDateFormat("dd MMM yyyy, hh:mm a", Locale.getDefault()).format(Date()),
            40f, y, sub); y += 14f
        c.drawLine(40f, y, 555f, y, line); y += 24f

        rows.forEach { (k, v) ->
            if (k == "—") { c.drawLine(40f, y - 8f, 555f, y - 8f, line); y += 10f; return@forEach }
            val bold = k.uppercase() == k && k.length > 4
            key.typeface = if (bold) Typeface.create("sans-serif", Typeface.BOLD) else Typeface.DEFAULT
            c.drawText(k, 40f, y, key)
            c.drawText(v, 555f, y, valP)
            y += 22f
        }

        y += 20f
        c.drawText("Generated by Pool Calculator", 40f, y, sub)

        doc.finishPage(page)
        val dir = File(ctx.cacheDir, "shared").apply { mkdirs() }
        val file = File(dir, "PoolEstimate_${System.currentTimeMillis()}.pdf")
        FileOutputStream(file).use { doc.writeTo(it) }
        doc.close()
        FileProvider.getUriForFile(ctx, "${ctx.packageName}.fileprovider", file)
    } catch (e: Exception) {
        Toast.makeText(ctx, "PDF failed: ${e.message}", Toast.LENGTH_LONG).show(); null
    }

    fun sharePdf(ctx: Context, uri: Uri) {
        val i = Intent(Intent.ACTION_SEND).apply {
            type = "application/pdf"
            putExtra(Intent.EXTRA_STREAM, uri)
            putExtra(Intent.EXTRA_SUBJECT, "Swimming Pool Estimate")
            addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
        }
        ctx.startActivity(Intent.createChooser(i, "Share estimate PDF"))
    }

    fun shareText(ctx: Context, text: String, whatsAppOnly: Boolean) {
        val i = Intent(Intent.ACTION_SEND).apply {
            type = "text/plain"
            putExtra(Intent.EXTRA_TEXT, text)
        }
        if (whatsAppOnly) {
            i.setPackage("com.whatsapp")
            try { ctx.startActivity(i); return }
            catch (e: Exception) {
                i.setPackage("com.whatsapp.w4b")
                try { ctx.startActivity(i); return }
                catch (e2: Exception) {
                    Toast.makeText(ctx, "WhatsApp not installed", Toast.LENGTH_SHORT).show()
                    i.setPackage(null)
                }
            }
        }
        ctx.startActivity(Intent.createChooser(i, "Share estimate"))
    }
}
